chore: cosmetics

diff --git a/.github/workflows/update-artifacts-file.yaml b/.github/workflows/update-artifacts-file.yaml
--- a/.github/workflows/update-artifacts-file.yaml
+++ b/.github/workflows/update-artifacts-file.yaml
@@ -67,12 +67,13 @@ jobs:
         git config --global user.name "mapcolonies[bot]"
         git config --global user.email "devops[bot]@mapcolonies.com"
 
+        git add .
+        # Add "|| true" for not failing on this line
+        git commit -m "Update artifacts.json" || true
+
         success=false
         for ((i=1; i<=5; i++)); do
           echo "Attempt number $i"
-          git add .
-          # Add "|| true" for not failing on this line
-          git commit -m "Update artifacts.json" || true
           if git push; then
             success=true
             break
